'use client'
import './globals.css'
import React from 'react'
import { Splash } from '@/components/Splash'
import { usePathname } from 'next/navigation'
import Aos from 'aos'
import 'aos/dist/aos.css'

import {
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
  Poppins,
} from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
})
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const isHome = pathname === '/'
  const [loading, setLoading] = React.useState(isHome)

  React.useEffect(() => {
    Aos.init({
      duration: 1500,
    })
  }, [])

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} ${poppins.variable} font-sans text-gray-100`}
      >
        {loading && isHome ? (
          <Splash finishLoading={() => setLoading(false)} />
        ) : (
          <div>{children}</div>
        )}
      </body>
    </html>
  )
}
